name: Troupe CI

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development ]

env:
  CARGO_TERM_COLOR: always

jobs:
  native_builds:
    name: Native Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        rust: [stable, beta, nightly]
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - uses: hecrj/setup-rust-action@v2
        with:
          rust-version: ${{ matrix.rust }}
          components: rustfmt
      - uses: actions/checkout@v4
      - run: cargo fmt --check
      - run: cargo build --verbose
      - run: cargo test --verbose
      - run: cargo doc --verbose
  wasm_build:
    name: Wasm Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [stable, beta, nightly]
    steps:
      - uses: hecrj/setup-rust-action@v2
        with:
          rust-version: ${{ matrix.rust }}
          targets: wasm32-unknown-unknown
      - uses: actions/checkout@v4
      - run: cargo build --target=wasm32-unknown-unknown --verbose
      - run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - run: wasm-pack test --headless --chrome --firefox --verbose
